### ISSUE TITLE
Crier not defined

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/lf-backup#11]
@jmkatcher  I attempted to run your latest fix that addressed issue #10 (restore path) but now I'm getting an error about "crier" not being defined:

```
$ lf-backup -C lf-backup4 -r 7 --prefix /data                                                    
restoring container lf-backup4
restoring file fh/fast/nelson_p/Ilsa/RNAseq/Xenografts/BAM/PCx_141.bam
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/lf-backup/lf_backup/lfbackup.py", line 199, in restore_file_mp
    restore_file(x[0],x[1].container,x[1].prefix)
  File "/root/lf-backup/lf_backup/lfbackup.py", line 192, in restore_file
    crier.info("lf-backup: restoring file %s" % filename)
NameError: name 'crier' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/lfbackup.py", line 9, in <module>
    load_entry_point('lf-backup', 'console_scripts', 'lfbackup.py')()
  File "/root/lf-backup/lf_backup/lfbackup.py", line 271, in main
    restore(parse_args,crier)
  File "/root/lf-backup/lf_backup/lfbackup.py", line 226, in restore
    p.map(restore_file_mp,r_files)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
NameError: name 'crier' is not defined
```

**Comment by jmkatcher** [comment]
I thought I was doing you a favor by enabling the restore syslog message not realizing that I wasn't passing the syslog object ('crier') to the restore work process.  Now checked in.

This is totally separate from the create dest directory functionality.

**Comment by robert-mcdermott** [comment]
@jmkatcher Just retested and everything works now; thanks

**Comment by jmkatcher** [comment]
Sorry for all the back and forth.  Thanks for your patience!
