### ISSUE TITLE
restore not working: name 'lflib' is not defined

### ISSUE THREAD

**Issue by robert-mcdermott** [FredHutch/lf-backup#9]
After install via pip on a clean test system the backup funtionality works, but when attempting to perform a restore, I get the following error:

```
$ lf-backup -C lf-backup4 -r 7 --prefix /restoredata
Traceback (most recent call last):
  File "/usr/local/bin/lfbackup.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lf_backup/lfbackup.py", line 271, in main
    restore(parse_args,crier)
  File "/usr/local/lib/python3.5/dist-packages/lf_backup/lfbackup.py", line 214, in restore
    c_objs=lflib.get_sw_container(parse_args.container)
NameError: name 'lflib' is not defined
```

**Comment by jmkatcher** [comment]
Sorry about that.  My development environment calls lflib as that's how that package is written.  The current lfbackup install copies it to lf_backup.

**Comment by robert-mcdermott** [comment]
@jmkatcher has the fixed version been pushed to PyPi yet?

**Comment by jmkatcher** [comment]
It's been checked in to github.
